name: Crush images
on:
  pull_request:
    branches:
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'
  # creates a button
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug      
jobs:
  crush:
    runs-on: [self-hosted, deepthought]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Crush images
        uses: crush-pics/crush-pics-github-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}

